name: srp_web
description: An absolute bare-bones web app.
version: 1.0.0
#homepage: https://www.example.com
#author: Didiet Noor <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  angular_forms: ^2.1.0
  angular_router: ^2.0.0-alpha+20
  http: ^0.12.0
  stream_transform: ^0.0.14+1
  crypto: ^2.0.1
  convert: ^2.0.2
  built_value: ^6.1.5

dev_dependencies:
  build_runner: ^1.1.0
  build_web_compilers: ^0.4.4+2
  angular_test: ^2.1.0
  build_test: ^0.10.3+3
  built_value_generator: ^6.1.5
