name: srp_web
description: An absolute bare-bones web app.
version: 1.0.0
#homepage: https://www.example.com
#author: Didiet Noor <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  angular_forms: ^2.1.0
  angular_router: ^2.0.0-alpha+20

dev_dependencies:
  build_runner: ^1.1.0
  build_web_compilers: ^0.4.4+2
  angular_test: ^2.1.0
  build_test: ^0.10.3+3
